# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Weave < Formula
  desc "A lightweight, extensible coding agent framework"
  homepage "https://github.com/weave-agent/weave"
  version "0.0.9"
  license "MIT"

  depends_on "go"
  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/weave-agent/weave/releases/download/v0.0.9/weave_0.0.9_darwin_amd64.tar.gz"
      sha256 "ded16863544de4ab41144793958a8297d7e6f0300eef78c6ee6b5c69497aa4d2"

      define_method(:install) do
        bin.install "weave"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/weave-agent/weave/releases/download/v0.0.9/weave_0.0.9_darwin_arm64.tar.gz"
      sha256 "407851c33692315c508d0cb9c6e2ce9b9b88a7e41b921123a5e0dfb15b7795dc"

      define_method(:install) do
        bin.install "weave"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/weave-agent/weave/releases/download/v0.0.9/weave_0.0.9_linux_amd64.tar.gz"
      sha256 "e98d301092ca4b0051284301310dd59b49f3715e3d2dc50cc5142ee6109e7d17"
      define_method(:install) do
        bin.install "weave"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/weave-agent/weave/releases/download/v0.0.9/weave_0.0.9_linux_arm64.tar.gz"
      sha256 "45f3ebb831501cce9d274ea9ac8dec4ad9f48e38973050c216c72a683c527da1"
      define_method(:install) do
        bin.install "weave"
      end
    end
  end

  test do
    system "#{bin}/weave", "--version"
  end
end
