# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Weave < Formula
  desc "A lightweight, extensible coding agent framework"
  homepage "https://github.com/weave-agent/weave"
  version "0.0.7"
  license "MIT"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/weave-agent/weave/releases/download/v0.0.7/weave_0.0.7_darwin_amd64.tar.gz"
      sha256 "8bd63d9d722224c07690349e76829bc72a454fbd4c70f69adc601336542f1d01"

      define_method(:install) do
        bin.install "weave"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/weave-agent/weave/releases/download/v0.0.7/weave_0.0.7_darwin_arm64.tar.gz"
      sha256 "138b4c087af3c1a7c57c417302ce1945d3ec704a7634a94f4c61f5c373375f58"

      define_method(:install) do
        bin.install "weave"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/weave-agent/weave/releases/download/v0.0.7/weave_0.0.7_linux_amd64.tar.gz"
      sha256 "141efce66b0b59d3d35647481ce7904bf2377ea7ef7fbfd3969bf6581406a8ea"
      define_method(:install) do
        bin.install "weave"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/weave-agent/weave/releases/download/v0.0.7/weave_0.0.7_linux_arm64.tar.gz"
      sha256 "33523e49b751d406c0527bf5cb8f974e28b9237b126e492ae99e1cebb5bfb8dd"
      define_method(:install) do
        bin.install "weave"
      end
    end
  end
end
